### ISSUE TITLE
imdb.mat not found

### ISSUE THREAD

**Issue by MimicryH** [albanie/mcnCrossModalEmotions#2]
When I run the script "run_distillation.m", there is an error " Unable to read file '/home/MatConvNet/matconvnet-1.0-beta25/data/emoVoxCeleb/imdb.mat'. No such file or directory. "
Could you please tell me how to produce emoVoxCeleb/imdb.mat?

**Comment by albanie** [comment]
Hi @McDobbie, apologies for the slow response.  Will push a fix shortly.

**Comment by albanie** [comment]
I've pushed an update which should download this file automatically, would you be able to check if this works for you?

**Comment by leafstark** [comment]
Now it works, thanks

**Comment by MimicryH** [comment]
Thanks!
