### ISSUE TITLE
No property 'normalise' a layer of type dagnn.SoftmaxCELoss

### ISSUE THREAD

**Issue by longinfield** [albanie/mcnCrossModalEmotions#3]
When I run the script run_distillation, there is an error No property 'normalise' a layer of type dagnn.SoftmaxCELoss.

**Comment by longinfield** [comment]
I add an property named 'normalise' in SoftmaxCELoss.m, it seems that it works but I'm not sure if it is a correct solution.

**Comment by albanie** [comment]
Hi @longinfield, apologies for the slow response.  This layer is found in [mcnExtraLayers](https://github.com/albanie/mcnExtraLayers) (I've updated the README to reflect this).

**Comment by Master32L** [comment]
Hi @albanie, I'm facing the same error as @longinfield. I don't understand his solution of adding a property to the layer. Can you help me?
