### ISSUE TITLE
Missing function  fetch_emoceleb_imdb and fetchExternalImdb

### ISSUE THREAD

**Issue by longinfield** [albanie/mcnCrossModalEmotions#5]
Hi, when I run the script student_states.m. It seems that the function fetch_emoceleb_imdb and fetchExternalImdb are missing. Could you please offer that?

**Comment by albanie** [comment]
Hi @longinfield, apologies - these were used in the original version of the code but are no longer required.  I have pushed an updated version which should hopefully address this.

**Comment by albanie** [comment]
Am closing for now, but feel free to re-open if still an issue.
