### ISSUE TITLE
Just use the student module alone?

### ISSUE THREAD

**Issue by lindagaw** [albanie/mcnCrossModalEmotions#6]
Hello,

I was wondering if it is possible to just use the student module alone to perform acoustics-based emotion recognition on wav files, or just use the teacher module alone to perform visual-based emotion recognition? 

Thanks!
Ash

**Comment by albanie** [comment]
Hi @lindagaw,

It should be OK to use the student model on its own, but one thing that will likely be needed is some finetuning (in our experiments we froze the student and added a learnable layer to match the distribution of emotions of each benchmark dataset). This was because (1) the number of emotions varies across datasets, but also (2) the training set for emotions is heavily biased, so while the embeddings produced by the student are useful, the raw predictions will be heavily skewed towards the training distribution (e.g. the student will often predict neutral).

**Comment by lindagaw** [comment]
Thank you for the advice! If there is a dataset with the exact same emotions present in the set used to train the student module and we want to evaluate that dataset, which module should be called? Or, how to call the student module on a wav file (or a set of wav files) without evoking the teacher module and obtain the classification result?

**Comment by albanie** [comment]
There is some code which is currently used to fine-tune the student for each benchmark (https://github.com/albanie/mcnCrossModalEmotions/blob/master/external/emo_benchmarks.m).  You could use the subfunction which just computes the audio features and apply it to your own dataset (here is the line where the model gets called: https://github.com/albanie/mcnCrossModalEmotions/blob/master/external/compute_audio_feats.m#L126), but unfortunately it will take a bit of coding to extract as a stand-alone module.

**Comment by lindagaw** [comment]
The module compute_audio_feats is called by student.stats with
`  compute_audio_feats(featPath, 'modelName', opts.student, ...
                                'targetDataset', 'emovoxceleb', ...
                                'teacher', opts.teacher) ;
`
If it's directly called upon a new dataset, what should each of the specified parameters (featPath, etc.) be? For example, instead of opt.student, what .m file should I specify as the value of 'modelName'?

Also, if I'm using my own dataset, 'targetDataset' will be changed. Is that sufficient to provide just the wav files? Do I have to import imdb? I'm asking this because the cases in  switch opts.targetDataset seem to have the variable getImdb. For example:

`  switch opts.targetDataset % NOTE: These need to be setup for your system
    case 'emovoxceleb'
      dataDir = fullfile(vl_rootnn, 'data/datasets/voxceleb1/voxceleb_all') ;
      getImdb = @(x) fetch_mod_emovoxceleb_imdb(opts.teacher, dataDir) ;
    otherwise, error('unknown dataset %s\n', opts.targetDataset) ;
  end
`

Sorry for having so many questions... I really appreciate your help!
